// 한국어 UI 텍스트 딕셔너리
export const t = {
  nav: {
    today: '오늘',
    mandarat: '만다라트',
    projects: '프로젝트',
    weekly: '주간 계획',
    review: '주간 리뷰',
    routines: '루틴',
    login: '로그인',
    logout: '로그아웃',
  },
  common: {
    add: '추가',
    save: '저장',
    delete: '삭제',
    remove: '제거',
    back: '뒤로',
    create: '생성',
    loading: '로딩 중...',
    error: '오류',
    cancel: '취소',
    confirm: '확인',
    edit: '수정',
    close: '닫기',
    done: '완료',
    todo: '할 일',
    active: '활성',
    inactive: '비활성',
  },
  pages: {
    todayTitle: '오늘',
    weeklyTitle: '주간 계획',
    reviewTitle: '주간 리뷰',
    routinesTitle: '루틴',
    projectsTitle: '프로젝트',
    mandaratTitle: '만다라트',
    loginTitle: '로그인',
    homeTitle: 'Pace Maker',
  },
  messages: {
    // Empty states
    todayEmpty: '오늘 실행할 작업이 없어요.',
    todayEmptyHelper: '주간 계획에서 \'오늘\'을 눌러 추가해보세요.',
    weeklyEmpty: '이번 달 집중 프로젝트를 먼저 선택해 주세요.',
    weeklyEmptyLink: '프로젝트 페이지로 이동',
    reviewEmpty: '이번 주 작업이 없습니다.',
    reviewEmptyLink: '주간 계획 페이지로 이동',
    routinesEmpty: '루틴이 없습니다.',
    routinesEmptyHelper: '위 폼을 사용하여 새 루틴을 추가하세요.',
    projectsEmpty: '프로젝트가 없습니다.',
    projectsEmptyHelper: '새 프로젝트를 생성해보세요.',
    
    // Helper texts
    todayHelper: 'Weekly에서 \'오늘\'을 눌러 추가하세요.',
    monthlyFocusMax: '최대 3개까지 선택',
    monthlyFocusNotice: '새 달이 시작되어 포커스가 초기화되었습니다.',
    routinesHelper: '활성 루틴을 이번 주 작업으로 추가합니다.',
    routineDuplicateNote: '일부 작업은 루틴과 중복되어 루틴 섹션에서만 표시됩니다.',
    
    // Actions
    saveAsRoutine: '루틴으로 저장',
    alreadyARoutine: '이미 루틴',
    addThisWeekRoutines: '이번 주 루틴 추가',
    addSelectedAsTasks: '선택한 항목을 주간 작업으로 추가',
    selectAll: '전체 선택',
    clear: '초기화',
    carryOver: '다음 주로 이월',
    carryOverSelected: '선택한 항목을 다음 주로 이월',
    removeFromToday: '오늘에서 제거',
    pickedForToday: '오늘',
    unpickFromToday: '오늘 해제',
    
    // Review
    overall: '전체',
    totalTasks: '총 작업',
    done: '완료',
    completionRate: '완료율',
    byProject: '프로젝트별',
    carryOverToNextWeek: '다음 주로 이월',
    carried: '이월됨',
    duplicatesSkipped: '중복 건너뜀',
    
    // Routines
    routineTitle: '제목',
    cadence: '반복',
    daily: '매일',
    weekly: '주간',
    daysOfWeek: '요일',
    addRoutine: '루틴 추가',
    
    // Projects
    monthlyFocus: '이번 달 집중',
    createProject: '프로젝트 생성',
    newProject: '새 프로젝트',
    focused: '집중',
    
    // Weekly
    weeklyPlanning: '주간 계획',
    projectActions: '프로젝트 액션 (만다라트에서)',
    addTask: '작업 추가',
    noActionItems: '액션 항목이 없습니다.',
    
    // Login
    login: '로그인',
    signup: '회원가입',
    email: '이메일',
    password: '비밀번호',
    continueWithGoogle: 'Google로 계속하기',
    continueWithKakao: '카카오로 계속하기',
    or: '또는',
    loggingIn: '로그인 중...',
    signingUp: '회원가입 중...',
    emailVerification: '이메일을 확인해주세요. 인증 링크를 보내드렸습니다.',
    loginError: '로그인 중 오류가 발생했습니다.',
    signupError: '회원가입 중 오류가 발생했습니다.',
    redirecting: '리다이렉트 중...',
  },
} as const
